### ISSUE TITLE
Already exists?

### ISSUE THREAD

**Issue by liuzhijun** [elliotcourant/arkdb#1]
https://github.com/pingcap/tidb

**Comment by elliotcourant** [comment]
It does, but this is aimed to be an embedded database comparable to SQLite. But with more concurrency. Rather than aiming to be a complete or primary database.

It's also using a different key value store, rather than using RocksDB or BoltDB, this is using Badger from dgraph.

This is just a personal experiment (and to learn) to build something to replace sqlite/rqlite in another project I'm working on.

**Comment by elliotcourant** [comment]
This project is also more closely related to https://gitlab.com/cznic/ql than anything, but uses the key value store instead of a custom built file format.

However this project does take advantage of TiDB's query parser because it is pure go.

**Comment by liuzhijun** [comment]
Thank you for your reply.
